-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQw4k+U/PQwhHZ+aw
G2eE/QLVI6+hMV1DkXUoMbqh/ROgCgYIKoZIzj0DAQehRANCAAT8i+CoPVbsLsYd
nK9kdf3R2F2StAjcl/VxQN+LXvFnofQWFsi4tySJuCPZCAuSZw8550sr+r8f5Ygv
jYrGYES4
-----END PRIVATE KEY-----